//
// Main.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Main: Codable {

    public var temp: Double?
    public var feelsLike: Double?
    public var tempMin: Double?
    public var tempMax: Double?
    public var pressure: Double?
    public var humidity: Double?

    public init(temp: Double?, feelsLike: Double?, tempMin: Double?, tempMax: Double?, pressure: Double?, humidity: Double?) {
        self.temp = temp
        self.feelsLike = feelsLike
        self.tempMin = tempMin
        self.tempMax = tempMax
        self.pressure = pressure
        self.humidity = humidity
    }

    public enum CodingKeys: String, CodingKey { 
        case temp
        case feelsLike = "feels_like"
        case tempMin = "temp_min"
        case tempMax = "temp_max"
        case pressure
        case humidity
    }


}

