//
// Wind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Wind: Codable {

    public var speed: Double?
    public var deg: Double?

    public init(speed: Double?, deg: Double?) {
        self.speed = speed
        self.deg = deg
    }


}

